import type { TaskEntity } from '../entities/TaskEntity';

export type AddTaskData = Omit<TaskEntity, 'id'>;// Data for adding a task, ID is generated by the repository

export type UpdateTaskData = Partial<Omit<TaskEntity, 'id'>> & { id: number };// Data for updating a task, ID is required, other fields optional or full entity

export interface TaskRepository {
  addTask(taskData: AddTaskData): Promise<TaskEntity>;
  removeTask(id: number): Promise<void>;
  updateTask(taskData: TaskEntity): Promise<TaskEntity>; // Or UpdateTaskData if partial updates are allowed at repo level
  getAllTasks(): Promise<TaskEntity[]>;
  getTask(id: number): Promise<TaskEntity | null>;
}